pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  HEROKU_API_KEY: $HEROKU_API
  HEROKU_APP: $HEROKU_APP

steps:
- script: |
   #!/bin/bash
   heroku container:login
   heroku container:push web --app $HEROKU_APP
   heroku container:release web --app $HEROKU_APP
    
  displayName: 'deploy to heroku'